[build]
pre-build = ["apt update && apt install libglib2.0-dev libmaliit-glib-dev -y"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update && apt install libglib2.0-dev:$CROSS_DEB_ARCH libmaliit-glib-dev:$CROSS_DEB_ARCH -y",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update && apt install libglib2.0-dev:$CROSS_DEB_ARCH libmaliit-glib-dev:$CROSS_DEB_ARCH -y",
]
